# 'bundle exec jekyll serve' to test
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Rahul C V
first_name: Rahul Reddy
middle_name: 
last_name: Chappidi Venkata
email: rc46@illinois.edu
description: >-
    Rahul C V
footer_text: >-
    Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rahulcvr.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# -----------------------------------------------------------------------------
# Socials
# -----------------------------------------------------------------------------

socials:
    # twitter:
    github: RahulCvr
    # instagram: swubear
    # last-fm: sarahwu_
    # goodreads: sarahawu

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
    publications:
        output: true
        permalink: /:collection/:name

    projects:
        output: true
        permalink: /projects/:name

# -----------------------------------------------------------------------------
# Build settings
# -----------------------------------------------------------------------------

markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
